language: node_js

services:
  - docker

env:
  - IMAGE=melonproject/ethereum-balance-watcher

script:
  - npm run compile
  - echo $IMAGE
  - docker build -t $IMAGE .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE
