language: node_js

node_js:
  - "8"

services:
  - docker

env:
  - IMAGE=melonproject/ethereum-balance-watcher

before_install:
  - npm install -g pkg

script:
  - npm run compile
  - echo $IMAGE
  - ls pkg/
  - docker build -t $IMAGE .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE
